const cartTypes = {
 SET_CART: 'SET_CART',
 TOGGLE_SIDE_CART: 'TOGGLE_SIDE_CART',
 SET_CART_LOAD: 'SET_CART_LOAD',
 SET_CART_START: 'SET_CART_START',
 SET_CART_END: 'SET_CART_END',
 ADD_TO_CART: 'ADD_TO_CART',
 UPDATE_CART: 'UPDATE_CART',
 SET_EDIT_ITEM: 'SET_EDIT_ITEM',
 SET_EDIT_TYPE: 'SET_EDIT_TYPE',
 FETCH_EDIT_ITEM_DATA:'FETCH_EDIT_ITEM_DATA',
 SET_EDIT_ITEM_DATA:'SET_EDIT_ITEM_DATA',
 UPDATE_EDIT_ITEM:'UPDATE_EDIT_ITEM',
 SET_EDIT_BUNDLE_DATA:'SET_EDIT_BUNDLE_DATA',
 UPDATE_EDIT_BUNDLE:'UPDATE_EDIT_BUNDLE',
 TYTB_UPDATE:'TYTB_UPDATE',
 CLEAR_CART:'CLEAR_CART'
};
export default cartTypes;
