require('./slick');
require('./sections');
require('./product-page');
require('./side-cart');
require('./common');
require('./simply-product');
require('./lastobject-landing-page')
require('./essential-mix-landing-page')
require('./topbar');
require('../scss/app.scss');