const globalActionTypes = {
  ITEM_ADD: "ITEM_ADD",
  ITEM_REMOVE: "ITEM_REMOVE",
  ADD_SELECTED_ITEM: "ADD_SELECTED_ITEM",
  ADD_SELECTED_BAG: "ADD_SELECTED_BAG",
  ADD_LOCAL_ITEM: "ADD_LOCAL_ITEM",
  ADD_LOCAL_BAG: "ADD_LOCAL_BAG",
  SET_ACTIVE_PRODUCT : 'SET_ACTIVE_PRODUCT',
  SET_CURRENT_PRODUCT : 'SET_CURRENT_PRODUCT',
  SET_CURRENT_COLLECTION: 'SET_CURRENT_COLLECTION',
  TOGGLE_DESCRIPTION_POPUP: 'TOGGLE_DESCRIPTION_POPUP',
  TOGGLE_HOW_TO_USE_POPUP: 'TOGGLE_HOW_TO_USE_POPUP',
  TOGGLE_SUSTAINIBILITY_POPUP: 'TOGGLE_SUSTAINIBILITY_POPUP',
  TOGGLE_INGREDIENTS_POPUP: 'TOGGLE_INGREDIENTS_POPUP'
};

export default globalActionTypes;
