export default{
    SET_QUIZ_LOADING: "SET_QUIZ_LOADING",
    CHANGE_QUIZ_STEP: "CHANGE_QUIZ_STEP",
    SET_QUIZ_SETTINGS:"SET_QUIZ_SETTINGS",
    SET_QUIZ_FORM_DATA:"SET_QUIZ_FORM_DATA",
    GET_QUIZ_FORM_DATA:"GET_QUIZ_FORM_DATA",
    SET_LOADER:'SET_LOADER'
}