const essentialTypes = {
  SET_LOADER : "SET_LOADER",
  SET_ESSENTIAL_DATA : "SET_ESSENTIAL_DATA",
  ADD_CHILD_PRODUCT : "ADD_CHILD_PRODUCT",
  SET_ADD_ITEMS_ERROR : "SET_ADD_ITEMS_ERROR",
  ADD_TO_CART_ESSENTIAL : "ADD_TO_CART_ESSENTIAL",
  UPDATE_UPSELL_PRODUCTS: "UPDATE_UPSELL_PRODUCTS" 
};

export default essentialTypes;
